controllers/ProxyController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Proxy;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use app\components\Y;

/**
 * ProxyController implements the CRUD actions for Proxy model.
 */
class ProxyController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete', 'list'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'list'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Proxy models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Proxy::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Proxy model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Proxy model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Proxy();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }



    /**
     * Updates an existing Proxy model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Proxy model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    /**
     * Finds the Proxy model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Proxy the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Proxy::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    /**
     * Creates a new Proxy model from list.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionList()
    {
        $model = new Proxy(['scenario' => 'list']);

        $count = 0;
        if (Yii::$app->request->post()) {

            $post = Yii::$app->request->post();
            $count = Proxy::addList($post);
        }

        return $this->render('list', [
            'model' => $model,
            'count' => $count
        ]);
    }

}

controllers/SearchController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Search;
use app\models\SearchSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use app\components\Y;

/**
 * SearchController implements the CRUD actions for Search model.
 */
class SearchController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete', 'approved', 'declined'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'approved', 'declined'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Search models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Search::find()->with(['city', 'region', 'category'])->orderBy('id DESC'),
        ]);

        $searchModel = new SearchSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Search model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Search model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Search();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Search model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Search model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Search model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Search the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Search::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    /**
     * @param $id
     * Подтверждаем запрос
     */
    public function actionApproved($id)
    {
        $model = $this->findModel($id);
        $model->active = 1;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * Отклоняем запрос
     */
    public function actionDeclined($id)
    {
        $model = $this->findModel($id);
        $model->active = 0;
        $model->save();

        return $this->redirect(['index']);
    }


    /**
     * Creates a new Proxy model from list.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionList()
    {
        $model = new Search(['scenario' => 'list']);

        $count = 0;
        if (Yii::$app->request->post()) {

            $post = Yii::$app->request->post();
            $count = Search::addList($post);
        }

        return $this->render('list', [
            'model' => $model,
            'count' => $count
        ]);
    }
}

controllers/SettingsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Settings;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use app\components\Y;

/**
 * SettingsController implements the CRUD actions for Settings model.
 */
class SettingsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Settings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $user = Users::getUser();
        $model = Settings::find()->where(['user_id' => $user->id])->one();

        return $this->redirect(['update', 'id' => $model->id]);
    }

    /**
     * Displays a single Settings model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Settings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Settings();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Settings model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Settings model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Settings model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Settings the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Settings::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\components\widgets\SettingsWidget;
use app\components\widgets\SeoWidget;


use app\models\Search;
use app\components\Y;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= $this->title ?></title>
        <?php $this->head() ?>
        <?= SettingsWidget::widget(['options' => 'verifications']) ?>

        <?= SeoWidget::widget() ?>

        <script type="application/ld+json">
        {
          "@context": "http://schema.org",
          "@type": "WebSite",
          "url": "<?= Y::domain(); ?>",
          "potentialAction": {
            "@type": "SearchAction",
            "target": "<?= Y::domain(); ?>/search/0/0/0?query={search_term_string}",
            "query-input": "required name=search_term_string"
          }
        }
        </script>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => 'Главная',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);

            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'encodeLabels' => false,
                'items' => [
                    !Yii::$app->user->isGuest ?
                        ['label' => 'Настройки', 'url' => ['/settings/index']] : '',
                    !Yii::$app->user->isGuest ?
                        ['label' => 'Поисковые запросы <span class="label label-warning">' . Search::countSearch() . '</span>', 'url' => ['/search/index']] : '',
                    !Yii::$app->user->isGuest ?
                        ['label' => 'Прокси', 'url' => ['/proxy/index']] : '',
                    Yii::$app->user->isGuest ? '' :
                        [
                            'label' => 'Выход (' . Yii::$app->user->identity->username . ')',
                            'url' => ['/site/logout'],
                            'linkOptions' => ['data-method' => 'post']
                        ],
                ],
            ]);
            NavBar::end();
            ?>

            <div class="container">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy; <?= date('Y') ?></p>
                <p class="pull-right"><?= Html::a('Полный список поисковых запросов', ['/site/queries']); ?></p>
            </div>
        </footer>

        <?php $this->endBody() ?>
        <?= SettingsWidget::widget(['options' => 'clickunder']) ?>
        <?= SettingsWidget::widget(['options' => 'otherAd']) ?>
        <?= SettingsWidget::widget(['options' => 'counters']) ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/redirect.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;
use app\components\widgets\SettingsWidget;
use app\components\widgets\SeoWidget;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
        <head>
            <meta charset="<?= Yii::$app->charset ?>">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <?= Html::csrfMetaTags() ?>
            <title><?= $this->title ?></title>
            <?php $this->head() ?>
            <?= SettingsWidget::widget(['options' => 'verifications']) ?>

            <?= SeoWidget::widget() ?>

            <style>

                .windows8 {
                    position: relative;
                    width: 30px;
                    height: 150px;
                    margin: 50px auto 0;
                }

                .windows8 .wBall {
                    position: absolute;
                    width: 44px;
                    height: 44px;
                    opacity: 0;
                    transform: rotate(225deg);
                    -o-transform: rotate(225deg);
                    -ms-transform: rotate(225deg);
                    -webkit-transform: rotate(225deg);
                    -moz-transform: rotate(225deg);
                    animation: orbit 3.9325s infinite;
                    -o-animation: orbit 3.9325s infinite;
                    -ms-animation: orbit 3.9325s infinite;
                    -webkit-animation: orbit 3.9325s infinite;
                    -moz-animation: orbit 3.9325s infinite;
                }

                .windows8 .wBall .wInnerBall {
                    position: absolute;
                    width: 6px;
                    height: 6px;
                    background: rgb(68, 157, 235);
                    left: 0px;
                    top: 0px;
                    border-radius: 6px;
                }

                .windows8 #wBall_1 {
                    animation-delay: 0.856s;
                    -o-animation-delay: 0.856s;
                    -ms-animation-delay: 0.856s;
                    -webkit-animation-delay: 0.856s;
                    -moz-animation-delay: 0.856s;
                }

                .windows8 #wBall_2 {
                    animation-delay: 0.173s;
                    -o-animation-delay: 0.173s;
                    -ms-animation-delay: 0.173s;
                    -webkit-animation-delay: 0.173s;
                    -moz-animation-delay: 0.173s;
                }

                .windows8 #wBall_3 {
                    animation-delay: 0.3465s;
                    -o-animation-delay: 0.3465s;
                    -ms-animation-delay: 0.3465s;
                    -webkit-animation-delay: 0.3465s;
                    -moz-animation-delay: 0.3465s;
                }

                .windows8 #wBall_4 {
                    animation-delay: 0.5095s;
                    -o-animation-delay: 0.5095s;
                    -ms-animation-delay: 0.5095s;
                    -webkit-animation-delay: 0.5095s;
                    -moz-animation-delay: 0.5095s;
                }

                .windows8 #wBall_5 {
                    animation-delay: 0.693s;
                    -o-animation-delay: 0.693s;
                    -ms-animation-delay: 0.693s;
                    -webkit-animation-delay: 0.693s;
                    -moz-animation-delay: 0.693s;
                }

                @keyframes orbit {
                    0% {
                        opacity: 1;
                        z-index: 99;
                        transform: rotate(180deg);
                        animation-timing-function: ease-out;
                    }

                    7% {
                        opacity: 1;
                        transform: rotate(300deg);
                        animation-timing-function: linear;
                        origin: 0%;
                    }

                    30% {
                        opacity: 1;
                        transform: rotate(410deg);
                        animation-timing-function: ease-in-out;
                        origin: 7%;
                    }

                    39% {
                        opacity: 1;
                        transform: rotate(645deg);
                        animation-timing-function: linear;
                        origin: 30%;
                    }

                    70% {
                        opacity: 1;
                        transform: rotate(770deg);
                        animation-timing-function: ease-out;
                        origin: 39%;
                    }

                    75% {
                        opacity: 1;
                        transform: rotate(900deg);
                        animation-timing-function: ease-out;
                        origin: 70%;
                    }

                    76% {
                        opacity: 0;
                        transform: rotate(900deg);
                    }

                    100% {
                        opacity: 0;
                        transform: rotate(900deg);
                    }
                }

                @-o-keyframes orbit {
                    0% {
                        opacity: 1;
                        z-index: 99;
                        -o-transform: rotate(180deg);
                        -o-animation-timing-function: ease-out;
                    }

                    7% {
                        opacity: 1;
                        -o-transform: rotate(300deg);
                        -o-animation-timing-function: linear;
                        -o-origin: 0%;
                    }

                    30% {
                        opacity: 1;
                        -o-transform: rotate(410deg);
                        -o-animation-timing-function: ease-in-out;
                        -o-origin: 7%;
                    }

                    39% {
                        opacity: 1;
                        -o-transform: rotate(645deg);
                        -o-animation-timing-function: linear;
                        -o-origin: 30%;
                    }

                    70% {
                        opacity: 1;
                        -o-transform: rotate(770deg);
                        -o-animation-timing-function: ease-out;
                        -o-origin: 39%;
                    }

                    75% {
                        opacity: 1;
                        -o-transform: rotate(900deg);
                        -o-animation-timing-function: ease-out;
                        -o-origin: 70%;
                    }

                    76% {
                        opacity: 0;
                        -o-transform: rotate(900deg);
                    }

                    100% {
                        opacity: 0;
                        -o-transform: rotate(900deg);
                    }
                }

                @-ms-keyframes orbit {
                    0% {
                        opacity: 1;
                        z-index: 99;
                        -ms-transform: rotate(180deg);
                        -ms-animation-timing-function: ease-out;
                    }

                    7% {
                        opacity: 1;
                        -ms-transform: rotate(300deg);
                        -ms-animation-timing-function: linear;
                        -ms-origin: 0%;
                    }

                    30% {
                        opacity: 1;
                        -ms-transform: rotate(410deg);
                        -ms-animation-timing-function: ease-in-out;
                        -ms-origin: 7%;
                    }

                    39% {
                        opacity: 1;
                        -ms-transform: rotate(645deg);
                        -ms-animation-timing-function: linear;
                        -ms-origin: 30%;
                    }

                    70% {
                        opacity: 1;
                        -ms-transform: rotate(770deg);
                        -ms-animation-timing-function: ease-out;
                        -ms-origin: 39%;
                    }

                    75% {
                        opacity: 1;
                        -ms-transform: rotate(900deg);
                        -ms-animation-timing-function: ease-out;
                        -ms-origin: 70%;
                    }

                    76% {
                        opacity: 0;
                        -ms-transform: rotate(900deg);
                    }

                    100% {
                        opacity: 0;
                        -ms-transform: rotate(900deg);
                    }
                }

                @-webkit-keyframes orbit {
                    0% {
                        opacity: 1;
                        z-index: 99;
                        -webkit-transform: rotate(180deg);
                        -webkit-animation-timing-function: ease-out;
                    }

                    7% {
                        opacity: 1;
                        -webkit-transform: rotate(300deg);
                        -webkit-animation-timing-function: linear;
                        -webkit-origin: 0%;
                    }

                    30% {
                        opacity: 1;
                        -webkit-transform: rotate(410deg);
                        -webkit-animation-timing-function: ease-in-out;
                        -webkit-origin: 7%;
                    }

                    39% {
                        opacity: 1;
                        -webkit-transform: rotate(645deg);
                        -webkit-animation-timing-function: linear;
                        -webkit-origin: 30%;
                    }

                    70% {
                        opacity: 1;
                        -webkit-transform: rotate(770deg);
                        -webkit-animation-timing-function: ease-out;
                        -webkit-origin: 39%;
                    }

                    75% {
                        opacity: 1;
                        -webkit-transform: rotate(900deg);
                        -webkit-animation-timing-function: ease-out;
                        -webkit-origin: 70%;
                    }

                    76% {
                        opacity: 0;
                        -webkit-transform: rotate(900deg);
                    }

                    100% {
                        opacity: 0;
                        -webkit-transform: rotate(900deg);
                    }
                }

                @-moz-keyframes orbit {
                    0% {
                        opacity: 1;
                        z-index: 99;
                        -moz-transform: rotate(180deg);
                        -moz-animation-timing-function: ease-out;
                    }

                    7% {
                        opacity: 1;
                        -moz-transform: rotate(300deg);
                        -moz-animation-timing-function: linear;
                        -moz-origin: 0%;
                    }

                    30% {
                        opacity: 1;
                        -moz-transform: rotate(410deg);
                        -moz-animation-timing-function: ease-in-out;
                        -moz-origin: 7%;
                    }

                    39% {
                        opacity: 1;
                        -moz-transform: rotate(645deg);
                        -moz-animation-timing-function: linear;
                        -moz-origin: 30%;
                    }

                    70% {
                        opacity: 1;
                        -moz-transform: rotate(770deg);
                        -moz-animation-timing-function: ease-out;
                        -moz-origin: 39%;
                    }

                    75% {
                        opacity: 1;
                        -moz-transform: rotate(900deg);
                        -moz-animation-timing-function: ease-out;
                        -moz-origin: 70%;
                    }

                    76% {
                        opacity: 0;
                        -moz-transform: rotate(900deg);
                    }

                    100% {
                        opacity: 0;
                        -moz-transform: rotate(900deg);
                    }
                }
            </style>

        </head>
        <body>
            <?php $this->beginBody() ?>
            <div class="container">
                <div class="windows8">
                    <div class="wBall" id="wBall_1">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_2">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_3">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_4">
                        <div class="wInnerBall"></div>
                    </div>
                    <div class="wBall" id="wBall_5">
                        <div class="wInnerBall"></div>
                    </div>
                </div>

                <div class="page-header">
                    <h3 class="text-center">Перенаправление. Ожидайте, пожалуйста.</h3>
                </div>
                <p class="text-center">При возникновении ошибки Вы можете вернуться к <a href="/">поиску</a></p>
            </div>
            <?php $this->endBody() ?>
        </body>
    </html>
<?php $this->endPage() ?>